In [1]:
import numpy as np

In [ ]:
a_list= [1,2,3,4,5, [1,2,3], "temat"] # nie idealna lista
k_krotka = (1,2,3,4,5, [1,2,3], "temat")
b_list = [1,2,3,4,5]
n_array = np.array(b_list) # wektor numpy


In [ ]:
a_list+b_list
n_array+n_array

array([ 2,  4,  6,  8, 10])

In [ ]:
a_list[3]

NameError: name 'k_list' is not defined

In [ ]:
a_list.append(100)
print(a_list)

[1, 2, 3, 4, 5, [1, 2, 3], 'temat', 100, 100]


In [ ]:
k_krotka[4]

5

In [ ]:
k_krotka.append(100)

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
np.array(b_list)+np.array(b_list)

array([ 2,  4,  6,  8, 10])

In [ ]:
n_array = np.array(a_list) # wektor numpy

In [ ]:
n_array

array([1, 2, 3, 4, 5, list([1, 2, 3]), 'temat'], dtype=object)

In [ ]:
#### Nowosci

studenci_slownik = {123: 123,"Igor":3, "Frankek":5, "Zosia":22,"Julia":[2,21], (1,2):"Krotka"}

In [ ]:
print(studenci_slownik)

{123: 123, 'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], (1, 2): 'Krotka'}


In [ ]:
studenci_slownik["Zosia"]

22

In [ ]:
for elementy in studenci_slownik:
    print(elementy)

print("*"*20)
for elementy in studenci_slownik.keys():
    print(elementy)

123
Igor
Frankek
Zosia
Julia
(1, 2)
********************
123
Igor
Frankek
Zosia
Julia
(1, 2)


In [ ]:
for elementy in studenci_slownik.items():
    print(elementy)

('Igor', 3)
('Frankek', 5)
('Zosia', 22)
('Julia', [2, 21])


In [ ]:
for elementy in studenci_slownik.values():
    print(elementy)

3
5
22
[2, 21]


In [ ]:
studenci_slownik["Cuthulu"]= -1000000

In [ ]:
studenci_slownik

{'Igor': 3, 'Frankek': 5, 'Zosia': 22, 'Julia': [2, 21], 'Cuthulu': -1000000}

In [ ]:
automatyczna_lista=[liczba**2 for liczba in range(100) if liczba%4==0]
print(automatyczna_lista)

[0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296, 1600, 1936, 2304, 2704, 3136, 3600, 4096, 4624, 5184, 5776, 6400, 7056, 7744, 8464, 9216]


In [ ]:
studenci = studenci_slownik.keys()
automatyczny_slownik=dict(para for para in enumerate(studenci))
print(automatyczny_slownik)

{0: 'Igor', 1: 'Frankek', 2: 'Zosia', 3: 'Julia', 4: 'Cuthulu'}


In [ ]:
##### zbiory

a={1,2,3,"Franek"}
b={2,3,4,"Franek"}


In [ ]:
a|b #suma zbiorów, sum of sets

{1, 2, 3, 4, 'Franek'}

In [ ]:
a.add("Franek")
print(a)

{1, 2, 3, 'Franek'}


In [ ]:
1 in a
"Igor" in studenci_slownik

True

### Własne typy

In [2]:
zajecia = [["wf"],
           ["informatyka", "nauka czytania"],
           ["relax", "jedzenie"],
           ["mispy","mispy w domu"],
           ["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"]
          ]

dnityg= ["Pon","Wto","Sro","Czwar","Pio"]

def dodaj_dwie_liczby(liczba1,liczba2):
    return liczba1+liczba2

In [4]:
class DzienZajec():
    """obiekt trzymający dany dzień zajęć i przypisane mu metody"""
    
    
    def __init__(self, lista_na_dany_dzien, nazwa_dnia): #definicja
        self.lista_zajec= lista_na_dany_dzien
        self.dzien = nazwa_dnia
        

    
    def ile_mispow(self):
        ile_m = sum([1 for zajecie in self.lista_zajec if "misp" in zajecie.lower()])
        return ile_m

    @property #zamienia na wlasciwosc   
    def ile_zajec(self):
        return len(self.lista_zajec)
    
    def __repr__(self):
        zajecia_do_stringa = ", ".join(self.lista_zajec)
        return "W dzien {} mam zajecia: {}".format(self.dzien, zajecia_do_stringa)
    

In [5]:
pio_zajecia = DzienZajec(["piateczek", "praca domowa z mispow", "Ilovemispy", "mispy w czasie snu"],
                        "piatek")

In [ ]:
pio_zajecia.ile_zajec

4

In [ ]:
print(pio_zajecia)

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu


In [ ]:
pio_zajecia.lista_zajec

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu']

In [7]:
pio_zajecia.lista_zajec.append("misp")
print(pio_zajecia.lista_zajec)

['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'misp']


In [8]:
pio_zajecia.ile_mispow()

4

In [9]:
print(pio_zajecia.lista_zajec)


['piateczek', 'praca domowa z mispow', 'Ilovemispy', 'mispy w czasie snu', 'misp']


In [10]:
pio_zajecia

W dzien piatek mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu, misp

In [ ]:
print(pio_zajecia.ile_zajec)

5


In [11]:
lista_zajec= [DzienZajec(lista_dzien, dzien) for lista_dzien, dzien in 
             zip(zajecia,dnityg)]

In [12]:
print(lista_zajec)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
posortowane_po_zajeciach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_zajec)
posortowane_po_mispach=sorted(lista_zajec, key= lambda zajecie: zajecie.ile_mispow())

In [ ]:
print(posortowane_po_zajeciach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


In [ ]:
print(posortowane_po_mispach)

[W dzien Pon mam zajecia: wf, W dzien Wto mam zajecia: informatyka, nauka czytania, W dzien Sro mam zajecia: relax, jedzenie, W dzien Czwar mam zajecia: mispy, mispy w domu, W dzien Pio mam zajecia: piateczek, praca domowa z mispow, Ilovemispy, mispy w czasie snu]


##### challenge 1

Stworz typ NumerTelefonu

 -- przy tworzeniu sprawdza czy właściwy numer (Polski) jeśli nie pisze, że error (ew. Exception)
 
 -- gdy printuję to mi pisze polskimi słowami i.e. "jeden, pięć, siedem, zero"
 
 -- gdy wywołuję właściwość wojewodzwtwo, podaje mi wojewodztwo ew. ze to komorkowy
 
 

In [164]:
class NumerTelefonu():
    """obekt numeru"""
    
    __area_codes = {75:"Dolnośląskie",76:"Dolnośląskie",74:"Dolnośląskie",
              71:"Dolnośląskie",52:"Kujawsko-pomorskie",56:"Kujawsko-pomorskie",
              54:"Kujawsko-pomorskie",83:"Lubelskie",82:"Lubelskie",81:"Lubelskie",
              84:"Lubelskie",95:"Lubuskie",68:"Lubuskie",42:"Łódzkie",44:"Łódzkie",
              43:"Łódzkie",46:"Łódzkie",12:"Małopolskie",18:"Małopolskie",14:"Małopolskie",
              23:"Mazowieckie",29:"Mazowieckie",24:"Mazowieckie",48:"Mazowieckie",
              25:"Mazowieckie",22:"Mazowieckie",77:"Opolskie",13:"Podkarpackie",
              16:"Podkarpackie",17:"Podkarpackie",15:"Podkarpackie",85:"Podlaskie",
              86:"Podlaskie",87:"Podlaskie",58:"Pomorskie",59:"Pomorskie",33:"Śląskie",
              34:"Śląskie",32:"Śląskie",41:"Świętokrzyskie",55:"Warmińsko-mazurskie",
              89:"Warmińsko-mazurskie",62:"Wielkopolskie",63:"Wielkopolskie",65:"Wielkopolskie",
              67:"Wielkopolskie",61:"Wielkopolskie",94:"Zachodnio-pomorskie",91:"Zachodnio-pomorskie"}

    __num_strings = ["zero","jeden","dwa","trzy","cztery",
                     "pięć","sześć","siedem","osiem","dziewięć"]
    
    def __init__(self, podany_numer): #definicja
        podany_numer=podany_numer.replace(" ","").replace("-","").replace("+","")
        if not podany_numer.isdigit() or len(podany_numer) != 9:
          raise ValueError("To nie jest poprawny numer telefonu")
          #print("numer niepoprawnu")
        self.numer=podany_numer
        print("numer poprawnu")

    @property #zamienia na wlasciwosc   
    def wojewodztwo(self):
        try:
          print(self.__area_codes[int(self.numer[0:2])]) 
        except:
          print("komórkowy")
    
    def __repr__(self):
        numer_slownie = ""
        for n in range(len(self.numer)):
          numer_slownie = numer_slownie+self.__num_strings[int(self.numer[n])]+" "
        return numer_slownie 

numer_dolnoslaskie = NumerTelefonu("756877868")

print(numer_dolnoslaskie.numer)
numer_dolnoslaskie.wojewodztwo
print(numer_dolnoslaskie)
print("="*80)
        
numer_lodz = NumerTelefonu("+42 687-78-68")

print(numer_lodz.numer)
numer_lodz.wojewodztwo
print(numer_lodz)
print("="*80)

numer_kom = NumerTelefonu("500100100")

print(numer_kom.numer)
numer_kom.wojewodztwo
print(numer_kom)
print("="*80)

numer_bad = NumerTelefonu("500bad100")

numer poprawnu
756877868
Dolnośląskie
siedem pięć sześć osiem siedem siedem osiem sześć osiem 
numer poprawnu
426877868
Łódzkie
cztery dwa sześć osiem siedem siedem osiem sześć osiem 
numer poprawnu
500100100
komórkowy
pięć zero zero jeden zero zero jeden zero zero 


ValueError: ignored

In [ ]:
# ma na takie rzeczy być w stanie odpowiedzieć

numer_lodz = NumerTelefonu("426877868")
>>> "prawidlowy numer"

numer_lodz.wojewodztwo 
>>> "Lodz"

print(numer_lodz)
>>> "cztery dwa sześć osiem siedem siedem osiem sześć osiem"